name: custom_post_quantum
description: "Dart implementation of NIST's post-quantum algorithm candidates, Kyber and Dilithium. which allows you to create Kyber with custom K"
version: 1.0.2-prerelease.8
repository: https://github.com/juanmadm88/custom_post_quantum

environment:
  sdk: ^3.4.0

dependencies:
  hashlib: ^1.16.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
